### ISSUE TITLE
请提高 PyTorch 版本上限

### ISSUE THREAD

**Issue by hongbo-miao** [opendatalab/MinerU#1643]
### Description of the bug | 错误描述

我之前发了个用 uv 安装的方法在 https://github.com/opendatalab/MinerU/discussions/1374#discussion-7750775

但我发现里面默认会用 paddlepaddle，我现在希望安装 paddlepaddle-gpu：

pyproject.toml

```toml
[project]
name = "mineru"
version = "1.0.0"
requires-python = "~=3.12.0"
dependencies = [
  "paddlepaddle-gpu==3.0.0b2",
]

[project.optional-dependencies]
build = [
  "setuptools",
  "torch",
]
compile = [
  "detectron2",
  "magic-pdf[full]==1.1.0",
]

[tool.uv]
package = false
prerelease = "allow"
no-build-isolation-package = ["detectron2"]

[tool.uv.sources]
paddlepaddle-gpu = { index = "paddlepaddle-gpu" }
detectron2 = { git = "https://github.com/facebookresearch/detectron2.git", branch = "main" }

[[tool.uv.index]]
name = "paddlepaddle-gpu"
url = "https://www.paddlepaddle.org.cn/packages/stable/cu123"
explicit = true
```

在跑 `uv sync --extra=build` 时会报错

```sh
warning: Missing version constraint (e.g., a lower bound) for `setuptools`
warning: Missing version constraint (e.g., a lower bound) for `torch`
  × No solution found when resolving dependencies for split (python_full_version >= '3.12.0' and python_full_version < '3.13' and platform_machine != 'aarch64' and platform_system == 'Linux'):
  ╰─▶ Because torch>=2.2.2,<=2.3.1 depends on nvidia-nvtx-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}==12.1.105 and only the following versions of torch are available:
          torch<=2.2.2
          torch==2.3.0
          torch>=2.3.1
      we can conclude that torch>=2.2.2,<=2.3.1 depends on nvidia-nvtx-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}==12.1.105.
      And because magic-pdf[full]==1.1.0 depends on torch>=2.2.2,<=2.3.1, we can conclude that magic-pdf[full]==1.1.0 depends on nvidia-nvtx-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}==12.1.105.
      And because paddlepaddle-gpu==3.0.0b2 depends on nvidia-nvtx-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}==12.4.127 and mineru[compile] depends on magic-pdf[full]==1.1.0, we can conclude that mineru[compile] and paddlepaddle-gpu==3.0.0b2 are
      incompatible.
      And because mineru[compile] depends on paddlepaddle-gpu==3.0.0b2 and your project requires mineru[compile], we can conclude that your project's requirements are unsatisfiable.
error: Recipe `uv-install-dependencies` failed on line 8 with exit code 1
```

但由于 magic-pdf 依赖的 PyTorch 版本太低：

https://github.com/opendatalab/MinerU/blob/1e4d4b596a29b78336a77d1db4ddcee8e4ba1b9a/setup.py#L40-L41

这个旧的 PyTorch 又依赖旧的 nvidia-nvtx-cu12。
而 paddlepaddle-gpu==3.0.0b2 需要更新的 nvidia-nvtx-cu12。

请提高 PyTorch 版本上限，谢谢！

### How to reproduce the bug | 如何复现

如上

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.12

### Software version | 软件版本 (magic-pdf --version)

1.1.0

### Device mode | 设备模式

cuda
